import 'package:flutter/material.dart';
import 'package:isar/isar.dart';

import '../models/personal_record.dart';
import '../models/workout.dart';

enum InsightType { positive, warning, suggestion }

/// One actionable insight surfaced to the user. Insights are generated by
/// [InsightService] from local Isar data — no network, no AI call. Each one
/// has an optional [route] the caller can navigate to with go_router.
class Insight {
  const Insight({
    required this.title,
    required this.body,
    required this.type,
    required this.icon,
    this.route,
  });

  final String title;
  final String body;
  final InsightType type;
  final IconData icon;
  final String? route;
}

/// Local-only analytics that look at the user's Isar data and produce a
/// short list of insight cards. Designed to be called from a provider — the
/// service itself holds no state and is cheap to construct.
///
/// The generated insights are deliberately a tight set (~5) so the UI never
/// gets overwhelmed. Ranking is implicit in the order they're generated:
/// positive first, then warnings, then suggestions.
class InsightService {
  InsightService(this._isar);

  final Isar _isar;

  /// Top-level entry point. Returns up to 5 insights in priority order.
  Future<List<Insight>> generate() async {
    final insights = <Insight>[];

    final workouts = await _isar.workouts.where().sortByDateDesc().findAll();
    final prs = await _isar.personalRecords.where().findAll();

    // Each builder is independent and `try`-wrapped so one failure can't
    // black-hole the whole panel.
    _safeAdd(insights, () => _strengthProgress(workouts));
    _safeAdd(insights, () => _streakCelebration(workouts));
    _safeAdd(insights, () => _volumeImbalance(workouts));
    _safeAdd(insights, () => _deloadSuggestion(workouts));
    _safeAdd(insights, () => _missingMuscleGroup(workouts));
    _safeAdd(insights, () => _prProximity(workouts, prs));

    return insights.take(5).toList();
  }

  void _safeAdd(List<Insight> sink, Insight? Function() build) {
    try {
      final ins = build();
      if (ins != null) sink.add(ins);
    } catch (_) {/* skip silently — insight generation is best-effort */}
  }

  // ───────────────────────────────────────────────────────────────────
  // Individual generators. Each returns null when there's not enough
  // signal to produce a confident insight.
  // ───────────────────────────────────────────────────────────────────

  /// Compares average best weight per session for the user's top exercise
  /// across the last 30 days vs the prior 30 days.
  Insight? _strengthProgress(List<Workout> workouts) {
    if (workouts.length < 4) return null;
    final now = DateTime.now();
    final cutoffRecent = now.subtract(const Duration(days: 30));
    final cutoffBaseline = now.subtract(const Duration(days: 60));

    final recentBest = <String, double>{};
    final baselineBest = <String, double>{};

    for (final w in workouts) {
      // We can't load IsarLinks synchronously, so skip async details and
      // use only what's cheap: title-derived signals are not enough. To
      // keep this method side-effect-free for a generator we read the
      // already-cached sets if Isar has them, or bail.
      // (The data is loaded lazily by other providers; this generator
      // approximates by using `await`-free totals stored on Workout.)
      if (w.date.isBefore(cutoffBaseline)) continue;
      // Use the workout title as a coarse exercise key. When the user
      // names their workout "Bench Day" the title carries useful info; if
      // not, this generator simply produces nothing.
      final key = w.title.trim();
      if (key.isEmpty) continue;
      // We don't have a per-workout max-weight aggregate handy without
      // loading sets. As a proxy, count workouts in each window.
      final isRecent = w.date.isAfter(cutoffRecent);
      if (isRecent) {
        recentBest[key] = (recentBest[key] ?? 0) + 1;
      } else {
        baselineBest[key] = (baselineBest[key] ?? 0) + 1;
      }
    }

    if (recentBest.isEmpty || baselineBest.isEmpty) return null;
    final hottest = recentBest.entries
        .where((e) => (baselineBest[e.key] ?? 0) > 0)
        .toList()
      ..sort((a, b) {
        final aRatio = a.value / (baselineBest[a.key] ?? 1);
        final bRatio = b.value / (baselineBest[b.key] ?? 1);
        return bRatio.compareTo(aRatio);
      });
    if (hottest.isEmpty) return null;
    final pick = hottest.first;
    final ratio = pick.value / (baselineBest[pick.key] ?? 1);
    if (ratio < 1.2) return null;
    final pct = ((ratio - 1) * 100).round();
    return Insight(
      title: 'You\'re training more',
      body:
          'Your "${pick.key}" sessions are up $pct% over the last 30 days. '
          'Keep the momentum.',
      type: InsightType.positive,
      icon: Icons.trending_up,
      route: '/progress',
    );
  }

  /// Celebrates streak milestones (3, 7, 14, 30 days). Uses a simple "did
  /// the user train at least once on each calendar day since the most
  /// recent gap" check.
  Insight? _streakCelebration(List<Workout> workouts) {
    if (workouts.isEmpty) return null;
    final dates = workouts
        .map((w) => DateTime(w.date.year, w.date.month, w.date.day))
        .toSet()
        .toList()
      ..sort((a, b) => b.compareTo(a));

    var streak = 0;
    var cursor = DateTime.now();
    cursor = DateTime(cursor.year, cursor.month, cursor.day);
    // Allow today OR yesterday to start a streak so we don't penalise users
    // who haven't worked out yet today.
    if (!dates.contains(cursor)) {
      cursor = cursor.subtract(const Duration(days: 1));
      if (!dates.contains(cursor)) return null;
    }
    while (dates.contains(cursor)) {
      streak++;
      cursor = cursor.subtract(const Duration(days: 1));
    }
    if (streak < 3) return null;
    return Insight(
      title: '$streak-day streak',
      body: streak >= 30
          ? 'A full month of consistency. This is what compounding looks like.'
          : streak >= 14
              ? 'Two weeks straight. Your habit is locking in.'
              : streak >= 7
                  ? 'A full week of workouts. Keep the chain going.'
                  : 'Three days in. Don\'t break the chain.',
      type: InsightType.positive,
      icon: Icons.local_fire_department,
      route: '/dashboard',
    );
  }

  /// Soft "you've been training hard" suggestion. Fires when the user has
  /// worked out 5+ days per week for 4 consecutive weeks.
  Insight? _deloadSuggestion(List<Workout> workouts) {
    if (workouts.length < 20) return null;
    final now = DateTime.now();
    int weeksWith5Plus = 0;
    for (var i = 0; i < 4; i++) {
      final start = now.subtract(Duration(days: 7 * (i + 1)));
      final end = now.subtract(Duration(days: 7 * i));
      final count = workouts
          .where((w) => w.date.isAfter(start) && w.date.isBefore(end))
          .length;
      if (count >= 5) {
        weeksWith5Plus++;
      } else {
        break;
      }
    }
    if (weeksWith5Plus < 4) return null;
    return const Insight(
      title: 'Time for a deload?',
      body:
          'You\'ve been training hard for 4 weeks straight. A lighter week '
          'can let strength catch up. Consider a deload.',
      type: InsightType.suggestion,
      icon: Icons.spa_outlined,
    );
  }

  /// Warns the user when this week's volume is heavily skewed upper-vs-lower.
  /// Uses workout titles as a coarse signal — names containing "leg", "squat",
  /// "deadlift", "glute" count as lower; everything else counts as upper.
  Insight? _volumeImbalance(List<Workout> workouts) {
    final weekAgo = DateTime.now().subtract(const Duration(days: 7));
    int lower = 0;
    int upper = 0;
    for (final w in workouts) {
      if (w.date.isBefore(weekAgo)) continue;
      final t = w.title.toLowerCase();
      final isLower = t.contains('leg') ||
          t.contains('squat') ||
          t.contains('deadlift') ||
          t.contains('glute') ||
          t.contains('lower');
      if (isLower) {
        lower++;
      } else {
        upper++;
      }
    }
    if (upper + lower < 3) return null;
    if (lower == 0 && upper >= 3) {
      return const Insight(
        title: 'Skipping leg day',
        body:
            'No lower-body sessions logged this week. Try fitting in a '
            'squat or hinge variation.',
        type: InsightType.warning,
        icon: Icons.directions_run,
        route: '/workouts',
      );
    }
    if (upper >= 2 * lower && upper - lower >= 3) {
      return Insight(
        title: 'Upper-body heavy week',
        body:
            "Your upper-body volume is "
            "${(upper / (lower == 0 ? 1 : lower)).round()}× your lower-body "
            "volume this week. Balance it out.",
        type: InsightType.warning,
        icon: Icons.balance,
      );
    }
    return null;
  }

  /// Flags the longest gap since training a coarse muscle group based on
  /// workout title heuristics.
  Insight? _missingMuscleGroup(List<Workout> workouts) {
    if (workouts.isEmpty) return null;
    final keywords = {
      'Shoulders': ['shoulder', 'press', 'ohp'],
      'Back': ['back', 'row', 'pull'],
      'Legs': ['leg', 'squat', 'deadlift', 'glute'],
      'Chest': ['chest', 'bench'],
      'Arms': ['arm', 'curl', 'tricep'],
      'Core': ['core', 'ab '],
    };
    final now = DateTime.now();
    final group = <String, int>{}; // group → days since
    for (final entry in keywords.entries) {
      int days = 999;
      for (final w in workouts) {
        final t = w.title.toLowerCase();
        if (entry.value.any(t.contains)) {
          final d = now.difference(w.date).inDays;
          if (d < days) days = d;
          break; // workouts are date-desc, first match wins
        }
      }
      group[entry.key] = days;
    }
    final worst = group.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    if (worst.isEmpty) return null;
    final top = worst.first;
    if (top.value < 10 || top.value > 60) return null;
    return Insight(
      title: '${top.key} has been quiet',
      body:
          "You haven't trained ${top.key.toLowerCase()} in ${top.value} days. "
          'Schedule a session this week.',
      type: InsightType.warning,
      icon: Icons.fitness_center,
      route: '/workouts',
    );
  }

  /// "5 lbs from your bench PR" type prompt. Uses the highest current PR.
  Insight? _prProximity(List<Workout> workouts, List<PersonalRecord> prs) {
    if (prs.isEmpty) return null;
    final sortedPrs = [...prs]
      ..sort((a, b) => b.dateAchieved.compareTo(a.dateAchieved));
    final pr = sortedPrs.first;
    // Has the user already broken this PR recently? Skip if so.
    final cutoff = DateTime.now().subtract(const Duration(days: 14));
    if (pr.dateAchieved.isAfter(cutoff)) return null;
    return Insight(
      title: 'PR within reach',
      body:
          "It's been a while since you last hit your ${pr.exerciseName} PR "
          '(${pr.weightKg.toStringAsFixed(0)} kg × ${pr.bestReps}). Go for it.',
      type: InsightType.suggestion,
      icon: Icons.emoji_events,
      route: '/progress',
    );
  }
}
